**Step 1 : Import packages**

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step 2 : Create a Dataframe using list**

In [3]:
Names=['Ramesh','Suresh','Satish']
#pd.Dataframe (data ,index,columns)
pd.DataFrame(Names)

        0
0  Ramesh
1  Suresh
2  Satish

In [ ]:
pd.DataFrame(Names,'Names') Wrong
pd.DataFrame(Names,columns='Names']) Wrons bcoz accepted type is aray
multiple list
pd.DataFrame(Names,['Names'])   wrong
pd.DataFrame(Names,columns=['Names'])  Correct

In [4]:
Names=['Ramesh','Suresh','Satish']
#pd.Dataframe (data ,index,columns)
pd.DataFrame(Names,columns=['Names'])

    Names
0  Ramesh
1  Suresh
2  Satish

**Step 3: Name the column**

In [ ]:
Names=['Ramesh','Suresh','Satish']
#pd.Dataframe (data ,index,columns)
pd.DataFrame(Names,'Names') #wrong 
pd.DataFrame(Names,columns='Names')  #w
pd.DataFrame(Names,['Names']) #w
pd.DataFrame(Names,columns=['Names']) #right

In [4]:
Names=['Ramesh','Suresh','Satish']
pd.DataFrame(Names,columns=['Names']) #right

    Names
0  Ramesh
1  Suresh
2  Satish

In [5]:
Names=['Ramesh','Suresh','Satish']
pd.DataFrame(Names,columns=['Naam']) #right

     Naam
0  Ramesh
1  Suresh
2  Satish

**Step 4 : Change the index**

In [8]:
Names=['Ramesh','Suresh','Satish']
pd.DataFrame(Names,index=["a","b","c"],columns=['namw'])

     namw
a  Ramesh
b  Suresh
c  Satish

**Step : 5 two columns**

In [11]:
Names=['Ramesh','Suresh','Satish']
Age=[20,22,35]
pd.DataFrame(columns=['name','age'])

Empty DataFrame
Columns: [name, age]
Index: []

In [ ]:
Names=['Ramesh','Suresh','Satish']
Age=[20,22,35]
pd.DataFrame(columns=['name','age'])

In [ ]:
Names=['Ramesh','Suresh','Satish']
age=[10,25,78]
pd.DataFrame(Names,index=["a","b","c"],columns=['namw'])

In [13]:
Names=['Ramesh','Suresh','Satish']
age=[10,25,78]
data=zip(Names,age)
cols=['Names','Age']
pd.DataFrame(data,columns=cols)

    Names  Age
0  Ramesh   10
1  Suresh   25
2  Satish   78

**Step 6: Add the data to empty data frame**

In [12]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
# selection or updatte we use square bracket[]
#function==()

In [10]:
Names=['Ramesh','Suresh','Satish']
age=[10,25,78]
data=zip(Names,age)
cols=['Names','Age']
employee=pd.DataFrame(data,columns=cols)
employee

    Names  Age
0  Ramesh   10
1  Suresh   25
2  Satish   78

In [11]:
employee['Names']

0    Ramesh
1    Suresh
2    Satish
Name: Names, dtype: object

In [ ]:
df=pd.DataFrame()
df['Names']    # it is do two operations selction or update

In [13]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df

    Names
0  Ramesh
1  Suresh
2  Satish

In [14]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']

KeyError: 'Age'

In [15]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22]
df

ValueError: Length of values (2) does not match length of index (3)

In [ ]:
Errors 
1 key error=no colummn available
2 Value error=column length is mismatched

In [16]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

In [ ]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22,24]
df

**Step 7 : already dataframe is available add the column to existing data frame**

In [19]:
df

    Names  Age     City
0  Ramesh   20      hyd
1  Suresh   22   mumbai
2  Satish   24  chennai

In [20]:
df['City']=['Pune','Mumbai','Delhi']
df

    Names  Age    City
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

**step 8: Rename the column**

- df.rename(mapper,index,columns,axis,inplace)
- A mapper is simply a conversion table / translation rule.
- “if you see this value, change it to that value”

In [22]:
#i want to change "City" to "city"
# do mapping for this for mapping we use dictionary {key value pair}
# create a dictionary
#d={'City':'city'}
# for this we need to change column
#where are you saying this to opython
#d={'City':'city'}
#df.rename(columns=d)
#df.rename(mapper,index,columns,axis,inplace)
d={'City':'city'}
df.rename(columns=d)

    Names  Age    city
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

In [26]:
d={'City':'city'} #columns
df.rename(d)   # index
df.rename(d,axis=0)  # index
df.rename(d,axis=1)  #column  work   row wise operation in column
df.rename(index=d)  # index
df.rename(columns=d)  # column  work

    Names  Age    city
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

In [28]:
df.rename(d,axis=1) 
df

    Names  Age    City
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

In [30]:
df.rename(d,axis=1)

    Names  Age    city
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

In [ ]:
df.rename(d,axis=1) 
we need to overright for new answer than previous will not
    show when we run the code doublw
Overwrite means replacing old data with new data.

inplace means:

make changes directly in the original DataFrame

inplace=True → original data changes permanently
inplace=False → original data stays same, new result is returned

In [ ]:
d={'City':'city'}
df.rename(columns=d)   # assume as axis =0 i need to change index  
# no chnage no error

In [23]:
df.rename(d)

    Names  Age    City
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

In [24]:
df.rename(d,axis=1)

    Names  Age    city
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

- use inplace for permanent changes

In [32]:
df.rename(d,axis=1,inplace=True)
df

    Names  Age    city
0  Ramesh   20    Pune
1  Suresh   22  Mumbai
2  Satish   24   Delhi

In [33]:
df.columns=['names','age','City']

In [34]:
df.index=['A','B','C']

In [35]:
df

    names  age    City
A  Ramesh   20    Pune
B  Suresh   22  Mumbai
C  Satish   24   Delhi

In [ ]:
axis=0 → work down the rows (column-wise)

This means the operation happens for each column.

axis=1 → work across columns (row-wise)

This means the operation happens for each row.

In [25]:
#i want to change "City" to "city"
#df.rename(mapper,index,columns,axis,inplace)
d={'City':'city'}
df.rename(columns=d)

     Names  Age     city     city
0   suhanu   20      hyd      hyd
1   ramesh   23   mumbai   mumbai
2  hjhfuhj   12  chennai  chennai

In [26]:
df=pd.DataFrame()
df['Names']=['suhanu','ramesh','hjhfuhj']
df['Age']=[20,23,12]
df['City']=['hyd','mumbai','chennai']
df

     Names  Age     City
0   suhanu   20      hyd
1   ramesh   23   mumbai
2  hjhfuhj   12  chennai

In [27]:
#df.rename(mapper,index,columns,axis,inplace)
d={'City':'city'}
df.rename(columns=d)

     Names  Age     city
0   suhanu   20      hyd
1   ramesh   23   mumbai
2  hjhfuhj   12  chennai

In [ ]:
d={'City':'city'}
df.rename(d)
df.rename(d,axis=0)  # index
df.rename(d,axis=1)   #col==work
df.rename(d,axis=0)     # index
df.rename(index=d)
df.rename(columns=d)   #column work

In [28]:
d={'City':'city'}
df.rename(d,axis=0)
df

     Names  Age     City
0   suhanu   20      hyd
1   ramesh   23   mumbai
2  hjhfuhj   12  chennai

In [29]:
d={'City':'city'}
df.rename(d,axis=0)

     Names  Age     City
0   suhanu   20      hyd
1   ramesh   23   mumbai
2  hjhfuhj   12  chennai

In [30]:
df.rename(d,axis=1)

     Names  Age     city
0   suhanu   20      hyd
1   ramesh   23   mumbai
2  hjhfuhj   12  chennai

In [31]:
df.rename(columns=d)

     Names  Age     city
0   suhanu   20      hyd
1   ramesh   23   mumbai
2  hjhfuhj   12  chennai

In [32]:
df.columns=['name','age','citty']

In [33]:
df

      name  age    citty
0   suhanu   20      hyd
1   ramesh   23   mumbai
2  hjhfuhj   12  chennai

In [34]:
df.index=['A','B','C']

In [35]:
df

      name  age    citty
A   suhanu   20      hyd
B   ramesh   23   mumbai
C  hjhfuhj   12  chennai

**Step 9 Drop the column**

In [ ]:
i want to drop city column

In [36]:
df

    names  age    City
A  Ramesh   20    Pune
B  Suresh   22  Mumbai
C  Satish   24   Delhi

In [42]:
df.drop('City',axis=1)   # here changes wont be permanent 
# when we write df old values will com 
# not writing df old new values will come

    names  age
A  Ramesh   20
B  Suresh   22
C  Satish   24

In [44]:
df.drop(columns=['City'])

    names  age
A  Ramesh   20
B  Suresh   22
C  Satish   24

In [46]:
df.drop('City',axis=1,inplace=True)
df   # writhing df old values will come 


### we want to use inplace for permanent changes

    names  age
A  Ramesh   20
B  Suresh   22
C  Satish   24

In [ ]:
df.drop('City')   error
df.drop('City',axis=0)  error
df.drop(index=['City'])  error
df.drop('City',axis=1)  work
df.drop(columns=['City']) work

In [ ]:
i want to drop satish

In [47]:
df.drop('C')

    names  age
A  Ramesh   20
B  Suresh   22

In [49]:
df   #we need to provide inplace for permanent changes

    names  age
A  Ramesh   20
B  Suresh   22
C  Satish   24

In [50]:
df.drop('C',inplace=True)

In [51]:
df

    names  age
A  Ramesh   20
B  Suresh   22

In [ ]:
df.drop()

- change the index
-  add the columns
-  add the data to empty dataframe
-  rename the column
-   rename all the column a

In [2]:
import pandas as pd

In [15]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [16]:
pd.df['Name']=['suresh','ramesh','satish']
pd.df['age']=[20,22,35]
pd.df['City']=['hyd','banglore','pune']
df

AttributeError: module 'pandas' has no attribute 'df'

In [2]:
import pandas as pd
df=pd.DataFrame()
pd.df['Name']=['suresh','ramesh','satish']
pd.df['age']=[20,22,35]
pd.df['City']=['hyd','banglore','pune']
df

AttributeError: module 'pandas' has no attribute 'df'

In [3]:
import pandas as pd

df = pd.DataFrame()

df['Name'] = ['suresh', 'ramesh', 'satish']
df['age'] = [20, 22, 35]
df['City'] = ['hyd', 'bangalore', 'pune']

print(df)

     Name  age       City
0  suresh   20        hyd
1  ramesh   22  bangalore
2  satish   35       pune

**replace**

In [4]:
df.replace(1,2)
df

     Name  age       City
0  suresh   20        hyd
1  ramesh   22  bangalore
2  satish   35       pune

In [ ]:
df.replace(to_replace,value)

In [6]:
df.replace('hyd','chennaai')

     Name  age       City
0  suresh   20   chennaai
1  ramesh   22  bangalore
2  satish   35       pune

In [53]:
Names=['Ramesh','Suresh','Satish']
City=['Hyd','Blr','Pune']
Age=[20,22,24]
data=zip(Names,City,Age)
df=pd.DataFrame(data,index=['A','B','C'],
                columns=['Names','City','Age'])
####################################
df.drop('City',axis=1,inplace=True)
df.drop('C',inplace=True)

In [54]:
df

    Names  Age
A  Ramesh   20
B  Suresh   22

**Session 67**

- create a dataframe
- name the column
- change the index
- add the data to empty dataframe
- add the column to existing dataframe
- rename the column
- rename all the column and all the index at a time
- drop the column
- drop the index

**step 10  replace**

In [60]:
import pandas as pd

df = pd.DataFrame()

df['Name'] = ['suresh', 'ramesh', 'satish',]
df['age'] = [20, 22, 24]
df['City'] = ['Hyd', 'Bangalore', 'Pune']

df

     Name  age       City
0  suresh   20        Hyd
1  ramesh   22  Bangalore
2  satish   24       Pune

In [59]:
df.replace('Hyd','Chennai')

     Name  age       City
0  suresh   20    Chennai
1  ramesh   24  Bangalore
2  satish   35       Pune

In [62]:
df = pd.DataFrame()

df['Name'] = ['suresh', 'ramesh', 'satish','Mahesh']
df['age'] = [20, 22, 24,24]
df['City'] = ['Hyd', 'Bangalore', 'Pune','Hyd']
df

     Name  age       City
0  suresh   20        Hyd
1  ramesh   22  Bangalore
2  satish   24       Pune
3  Mahesh   24        Hyd

In [63]:
df.replace('Hyd','Chennai')

     Name  age       City
0  suresh   20    Chennai
1  ramesh   22  Bangalore
2  satish   24       Pune
3  Mahesh   24    Chennai

In [64]:
df['Marks']=[25,24,23,22]

In [65]:
df

     Name  age       City  Marks
0  suresh   20        Hyd     25
1  ramesh   22  Bangalore     24
2  satish   24       Pune     23
3  Mahesh   24        Hyd     22

In [66]:
df.replace(24,20) #when we chnage marks 24 than age also will change

     Name  age       City  Marks
0  suresh   20        Hyd     25
1  ramesh   22  Bangalore     20
2  satish   20       Pune     23
3  Mahesh   20        Hyd     22

In [ ]:
#all the data in same will change
#all the column data will change

In [68]:
df['Marks'].replace(24,20,inplace=True)
df

C:\Users\suhan\AppData\Local\Temp\ipykernel_26616\2409022249.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].replace(24,20,inplace=True)

     Name  age       City  Marks
0  suresh   20        Hyd     25
1  ramesh   22  Bangalore     20
2  satish   24       Pune     23
3  Mahesh   24        Hyd     22

In [ ]:
i want to change city name to chennai
for thr candidates who has age = 24

In [ ]:
  here both side hyd chnage all chnage but i dont want change

In [18]:
df['Marks']=[45,23,89]
df

     Name  age       City  Marks
0  suresh   20        hyd     45
1  ramesh   24  bangalore     23
2  satish   35       pune     89
3  mahesh   34        hyd     45

In [15]:
df['Marks'].replace(23,77.inplace=True)

<>:1: SyntaxWarning: invalid decimal literal
<>:1: SyntaxWarning: invalid decimal literal
C:\Users\suhan\AppData\Local\Temp\ipykernel_10020\3050866215.py:1: SyntaxWarning: invalid decimal literal
  df['Marks'].replace(23,77.inplace=True)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3050866215.py, line 1)

**step 11 np.where**

In [69]:
import numpy as np

In [ ]:
i want to change city name to chennai
for the candidates who has age =24

In [ ]:
np.where(condition,True,False)
age==24
Chennai  if condition is true print chennai
Nochange   if cond is false no change

In [71]:
# i need to apply condition on age column
# we need to slect a column
df['age']

0    20
1    22
2    24
3    24
Name: age, dtype: int64

In [78]:
con=df['age']==24
true='Chennai'
false=df['City']

In [79]:
np.where(con,true,'aaa')

array(['aaa', 'aaa', 'Chennai', 'Chennai'], dtype='<U7')

In [80]:
np.where(con,true,false)

array(['Hyd', 'Bangalore', 'Chennai', 'Chennai'], dtype=object)

In [81]:
df['City']=np.where(con,true,false)

In [82]:
df

     Name  age       City  Marks
0  suresh   20        Hyd     25
1  ramesh   22  Bangalore     20
2  satish   24    Chennai     23
3  Mahesh   24    Chennai     22

**loc-iloc**

In [ ]:
df.loc[rows,columns]
rows are index numbers similar to list slice
l[start:stop:step]
column are names any cloumn name we can provide
df.iloc[rows,columns]
rows and columns are index numbers similar to list slice
l[start:stop:step]

In [85]:

df.loc[[1,2,3]]

     Name  age       City  Marks
1  ramesh   22  Bangalore     20
2  satish   24    Chennai     23
3  Mahesh   24    Chennai     22

In [86]:
rows=[1,2,3]
cols=['age','City']
df.loc[rows,cols]

   age       City
1   22  Bangalore
2   24    Chennai
3   24    Chennai

In [88]:
rows=[1,2,3]
df.iloc[rows]

     Name  age       City  Marks
1  ramesh   22  Bangalore     20
2  satish   24    Chennai     23
3  Mahesh   24    Chennai     22

In [89]:
rows=[1,2,3]
cols=[1,2]
df.iloc[rows,cols]

   age       City
1   22  Bangalore
2   24    Chennai
3   24    Chennai

In [90]:
cols=[1,2]
df.iloc[1:3,cols]

   age       City
1   22  Bangalore
2   24    Chennai

In [92]:
cols=['age','City']
df.loc[1:3,cols]

   age       City
1   22  Bangalore
2   24    Chennai
3   24    Chennai

In [94]:
cols=[1,2]
df.iloc[1:3,cols]

   age       City
1   22  Bangalore
2   24    Chennai

In [95]:
df.loc[0]

Name     suresh
age          20
City        Hyd
Marks        25
Name: 0, dtype: object

In [96]:
df.loc[1]

Name        ramesh
age             22
City     Bangalore
Marks           20
Name: 1, dtype: object

In [97]:
df.loc[3]

Name      Mahesh
age           24
City     Chennai
Marks         22
Name: 3, dtype: object

In [ ]:
4th row nahi hai toh add krna

**appending a data**

In [103]:
df.loc[4]=['Anish',26,'Mumbai',25]

In [104]:
df

#df.loc[len(df)]=['Anish',26,'Mumbai',25]   we can do like this also i do 
# this than two values will come

     Name  age       City  Marks
0  suresh   20        Hyd     25
1  ramesh   22  Bangalore     20
2  satish   24    Chennai     23
3  Mahesh   24    Chennai     22
4   Anish   26     Mumbai     25
5   Anish   26     Mumbai     25

**step 13 how t save the data frame**

In [108]:
# directory : where is the file available
# name =: what is the name of the file
# extension : what is the type of the file

#dataframe variable==df
#name  :  student
#exten  : .csv and .xlsx
df.to_csv('student.csv')

In [109]:
pd.read_csv('student.csv')

   Unnamed: 0    Name  age       City  Marks
0           0  suresh   20        Hyd     25
1           1  ramesh   22  Bangalore     20
2           2  satish   24    Chennai     23
3           3  Mahesh   24    Chennai     22
4           4   Anish   26     Mumbai     25
5           5   Anish   26     Mumbai     25

In [111]:
df.to_excel('student.xlsx')

In [112]:
df.to_csv('student.csv', index=False)

In [113]:
import os
print(os.getcwd())

C:\Users\suhan\OneDrive\Documents\Naresh_IT\EDA

In [114]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Session_1_Basics.ipynb', 'student.csv', 'student.xlsx']

In [115]:
import os
os.startfile('student.xlsx')

In [2]:
import pandas as pd

In [3]:
pd.read_csv(r"C:\Users\suhan\OneDrive\Documents\Naresh_IT\Data Files\Visadataset.csv")

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [4]:
pd.read_csv(r"C:\Users\suhan\OneDrive\Documents\Naresh_IT\Data Files\bank.csv")

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [4]:
import pandas as pd

In [5]:
pd.read_csv(r"C:\Users\suhan\OneDrive\Documents\Naresh_IT\Data Files\bank.csv",
            sep=';')

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [6]:
visa_df=pd.read_csv(r"C:\Users\suhan\OneDrive\Documents\Naresh_IT\Data Files\Visadataset.csv")

- head
- tail
- shape
- size
- columns
- dtypes
- isnull
- info

In [7]:
visa_df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [8]:
visa_df.shape

(25480, 12)

In [9]:
visa_df.tail()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [10]:
visa_df.size

305760

In [11]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [12]:
visa_df.isnull

<bound method DataFrame.isnull of          case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N
1         EZYV02      Asia              Master's                  Y
2         EZYV03      Asia            Bachelor's                  N
3         EZYV04      Asia            Bachelor's                  N
4         EZYV05    Africa              Master's                  Y
...          ...       ...                   ...                ...
25475  EZYV25476      Asia            Bachelor's                  Y
25476  EZYV25477      Asia           High School                  Y
25477  EZYV25478      Asia              Master's                  Y
25478  EZYV25479      Asia              Master's                  Y
25479  EZYV25480      Asia            Bachelor's                  Y

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007
1                         N             2412         2002
2                         Y            44444         2008
3                         N               98         1897
4                         N             1082         2005
...                     ...              ...          ...
25475                     Y             2601         2008
25476                     N             3274         2006
25477                     N             1121         1910
25478                     Y             1918         1887
25479                     N             3195         1960

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y
1                Northeast       83425.6500         Year                  Y
2                     West      122996.8600         Year                  Y
3                     West       83434.0300         Year                  Y
4                    South      149907.3900         Year                  Y
...                    ...              ...          ...                ...
25475                South       77092.5700         Year                  Y
25476            Northeast      279174.7900         Year                  Y
25477                South      146298.8500         Year                  N
25478                 West       86154.7700         Year                  Y
25479              Midwest       70876.9100         Year                  Y

      case_status
0          Denied
1       Certified
2          Denied
3          Denied
4       Certified
...           ...
25475   Certified
25476   Certified
25477   Certified
25478   Certified
25479   Certified

[25480 rows x 12 columns]>

In [13]:
visa_df.info

<bound method DataFrame.info of          case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N
1         EZYV02      Asia              Master's                  Y
2         EZYV03      Asia            Bachelor's                  N
3         EZYV04      Asia            Bachelor's                  N
4         EZYV05    Africa              Master's                  Y
...          ...       ...                   ...                ...
25475  EZYV25476      Asia            Bachelor's                  Y
25476  EZYV25477      Asia           High School                  Y
25477  EZYV25478      Asia              Master's                  Y
25478  EZYV25479      Asia              Master's                  Y
25479  EZYV25480      Asia            Bachelor's                  Y

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007
1                         N             2412         2002
2                         Y            44444         2008
3                         N               98         1897
4                         N             1082         2005
...                     ...              ...          ...
25475                     Y             2601         2008
25476                     N             3274         2006
25477                     N             1121         1910
25478                     Y             1918         1887
25479                     N             3195         1960

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y
1                Northeast       83425.6500         Year                  Y
2                     West      122996.8600         Year                  Y
3                     West       83434.0300         Year                  Y
4                    South      149907.3900         Year                  Y
...                    ...              ...          ...                ...
25475                South       77092.5700         Year                  Y
25476            Northeast      279174.7900         Year                  Y
25477                South      146298.8500         Year                  N
25478                 West       86154.7700         Year                  Y
25479              Midwest       70876.9100         Year                  Y

      case_status
0          Denied
1       Certified
2          Denied
3          Denied
4       Certified
...           ...
25475   Certified
25476   Certified
25477   Certified
25478   Certified
25479   Certified

[25480 rows x 12 columns]>

In [14]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [15]:
type(visa_df)

pandas.core.frame.DataFrame

In [16]:
type(visa_df.columns)

pandas.core.indexes.base.Index

In [17]:
cols=visa_df.columns
cols.tolist()

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'no_of_employees',
 'yr_of_estab',
 'region_of_employment',
 'prevailing_wage',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [18]:
cols=visa_df.columns
cols.tolist().index('continent')

1

**data types**

In [19]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [ ]:
   # ()  is needed and you not provided than bound methos will come
   # () is not needed than not callable come

In [20]:
data_types=visa_df.dtypes

- series does not have any column name
- data frame have column name
- series is a kry value pair

In [21]:
data_types=visa_df.dtypes

In [26]:
type(data_types)

pandas.core.series.Series

In [27]:
type(visa_df)

pandas.core.frame.DataFrame

- series is a key value pair
- series kind of a dictionary

In [22]:
data_types.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [23]:
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [24]:
data_types.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [ ]:
data_types.keys()
data_types.values
##################
data_types.index
data_types.values

- When we have a series
- we need to make to separate lists
- so that we can able to create a dataframe

In [25]:
visa_df.dtypes # data frame (we starts from here)
keys=visa_df.dtypes.keys() # types series
values=visa_df.dtypes.values #keys
df1=pd.DataFrame(zip(keys,values),  #values
             columns=['Continent','Datatype'])
df1

                Continent Datatype
0                 case_id   object
1               continent   object
2   education_of_employee   object
3      has_job_experience   object
4   requires_job_training   object
5         no_of_employees    int64
6             yr_of_estab    int64
7    region_of_employment   object
8         prevailing_wage  float64
9            unit_of_wage   object
10     full_time_position   object
11            case_status   object

- separate categorical and numerical column in different list

In [26]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
cat,num=[],[]
for i,j in zip(keys,values):
    if j=='object':
        cat.append(i)
    else:
        num.append(i)
cat,num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 ['no_of_employees', 'yr_of_estab', 'prevailing_wage'])

In [40]:
cat = []
num = []

for col in visa_df.columns:
    if visa_df[col].dtype == 'object':
        cat.append(col)
    else:
        num.append(col)

cat, num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 ['no_of_employees', 'yr_of_estab', 'prevailing_wage'])

In [92]:
visa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                25480 non-null  object
 1   continent              25480 non-null  object
 2   education_of_employee  25480 non-null  object
 3   has_job_experience     25480 non-null  object
 4   requires_job_training  25480 non-null  object
 5   no_of_employees        25480 non-null  int64
 6   yr_of_estab            25480 non-null  int64
 7   region_of_employment   25480 non-null  object
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object
 10  full_time_position     25480 non-null  object
 11  case_status            25480 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

In [97]:
keys=visa_df.keys()
keys
cat=[]
num=[]
for i in keys:
    if visa_df[i].dtypes=='object':
        cat.append(i)
    else:
        num.append(i)

cat,num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 ['no_of_employees', 'yr_of_estab', 'prevailing_wage'])

In [27]:
visa_df.iloc[100:105,3:7]   #dataframe

    has_job_experience requires_job_training  no_of_employees  yr_of_estab
100                  Y                     N             2227         2007
101                  Y                     N              334         2007
102                  Y                     N              224         2008
103                  Y                     N              367         1982
104                  Y                     N              306         2003

In [29]:
visa_df.loc[100:105]  #s

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
101,EZYV102,Asia,Master's,Y,N,334,2007,Midwest,43421.88,Year,Y,Certified
102,EZYV103,Asia,Bachelor's,Y,N,224,2008,Midwest,80253.78,Year,Y,Certified
103,EZYV104,Asia,Doctorate,Y,N,367,1982,West,115235.95,Year,Y,Certified
104,EZYV105,Asia,Master's,Y,N,306,2003,Northeast,95200.86,Year,N,Certified
105,EZYV106,North America,Doctorate,Y,N,2317,1995,Island,41613.52,Year,Y,Certified

In [30]:
visa_df.iloc[100] #series

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [107]:
visa_df.loc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [31]:
visa_df.iloc[[100]]       #dataframe

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [108]:
visa_df.loc[[100]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [32]:
visa_df.iloc[[100,200,300],]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [34]:
visa_df.iloc[[100,200,300],:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [110]:
visa_df.loc[[100,200,300],]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [35]:
visa_df.iloc[[100,200,300],:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [36]:
visa_df.iloc[:,[3,6,9]]

      has_job_experience  yr_of_estab unit_of_wage
0                      N         2007         Hour
1                      Y         2002         Year
2                      N         2008         Year
3                      N         1897         Year
4                      Y         2005         Year
...                  ...          ...          ...
25475                  Y         2008         Year
25476                  Y         2006         Year
25477                  Y         1910         Year
25478                  Y         1887         Year
25479                  Y         1960         Year

[25480 rows x 3 columns]

In [38]:
visa_df.iloc[:,3]

0        N
1        Y
2        N
3        N
4        Y
        ..
25475    Y
25476    Y
25477    Y
25478    Y
25479    Y
Name: has_job_experience, Length: 25480, dtype: object

In [39]:
visa_df.iloc[:,[3]]

      has_job_experience
0                      N
1                      Y
2                      N
3                      N
4                      Y
...                  ...
25475                  Y
25476                  Y
25477                  Y
25478                  Y
25479                  Y

[25480 rows x 1 columns]

In [41]:
visa_df.iloc[:,:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [57]:
cat = []
num = []

for col, dtype in zip(visa_df.columns, visa_df.dtypes):
    if dtype == 'object':
        cat.append(col)
    else:
        num.append(col)

cat, num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 ['no_of_employees', 'yr_of_estab', 'prevailing_wage'])

In [60]:
bank_df=pd.read_csv(r"C:\Users\suhan\OneDrive\Documents\Naresh_IT\Data Files\bank.csv",
            sep=';')
bank_df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [ ]:
head
tail
shape
size
columns
dtypes
isnull
info

In [61]:
bank_df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [62]:
bank_df.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [63]:
bank_df.shape

(4521, 17)

In [64]:
bank_df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [65]:
bank_df.size

76857

In [66]:
bank_df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [94]:
bank_df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [95]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [98]:
bank_df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [101]:
keys=bank_df.keys()
keys

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [102]:
keys=bank_df.keys()
cat=[]
num=[]
for i in keys:
    if bank_df[i].dtypes=='object':
        cat.append(i)
    else:
        num.append(i)
cat,num

(['job',
  'marital',
  'education',
  'default',
  'housing',
  'loan',
  'contact',
  'month',
  'poutcome',
  'y'],
 ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'])